### ISSUE TITLE
文档多处错误

### ISSUE THREAD

**Issue by koushiyu** [huaqingyi/egg-pandora#1]
egg-pandora 拼写成egg-pandoras

控制器实例有误 采用匿名类会报错

**Comment by huaqingyi** [comment]
markdown explain to fix . my up the time is busy . sorry just now for edit the explain .

**Comment by huaqingyi** [comment]
> egg-pandora 拼写成egg-pandoras
> 
> 控制器实例有误 采用匿名类会报错

已修改，最近有点忙
